package com.example.demospring.entity;
// Generated Jun 26, 2021 8:44:47 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name="department")
public class Department  implements java.io.Serializable {


     private String code;
     private Status status;
     private String description;

    public Department() {
    }

	
    public Department(String code) {
        this.code = code;
    }
    public Department(String code, Status status, String description) {
       this.code = code;
       this.status = status;
       this.description = description;
    }
   
     @Id 
    
    @Column(name="code", unique=true, nullable=false, length=16)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    
    @Column(name="description", length=128)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


