package com.example.demospring.entity;
// Generated Jun 26, 2021 8:44:47 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name="status")
public class Status  implements java.io.Serializable {


     private String code;
     private String description;
     private Set<Department> departments = new HashSet<Department>(0);

    public Status() {
    }

	
    public Status(String code) {
        this.code = code;
    }
    public Status(String code, String description, Set<Department> departments) {
       this.code = code;
       this.description = description;
       this.departments = departments;
    }
   
     @Id 
    
    @Column(name="code", unique=true, nullable=false, length=16)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    @Column(name="description", length=128)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="status")
    public Set<Department> getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Set<Department> departments) {
        this.departments = departments;
    }




}


